
(base) C:\Users\ST186052>dir
 ドライブ C のボリューム ラベルは OS です
 ボリューム シリアル番号は 1EB9-76A5 です

 C:\Users\ST186052 のディレクトリ

2019/03/22  10:36    <DIR>          .
2019/03/22  10:36    <DIR>          ..
2018/05/07  11:43    <DIR>          .atom
2018/12/13  20:28    <DIR>          .conda
2018/12/13  13:26                43 .condarc
2018/09/05  11:50               126 .defaults-0.1.0.ini
2018/09/12  06:53    <DIR>          .eclipse
2019/03/19  11:09               216 .gitconfig
2018/11/28  11:55    <DIR>          .ipynb_checkpoints
2018/04/09  13:46    <DIR>          .ipython
2018/04/10  13:05    <DIR>          .jupyter
2019/01/21  00:22    <DIR>          .keras
2018/12/13  22:48    <DIR>          .matplotlib
2018/09/21  11:06    <DIR>          .plotly
2018/12/18  18:30    <DIR>          .pylint.d
2018/09/10  17:09    <DIR>          .QtWebEngineProcess
2019/03/21  17:59    <DIR>          .spyder-py3
2019/03/19  15:53    <DIR>          .ssh
2018/09/10  17:09    <DIR>          .Tableau Reader
2019/03/19  11:07               996 .viminfo
2018/11/21  14:42    <DIR>          .vscode
2018/08/06  15:27    <DIR>          3D Objects
2019/03/19  16:22    <DIR>          analytics
2018/08/12  15:37    <DIR>          cache
2019/01/22  16:39    <DIR>          Contacts
2019/03/22  10:52    <DIR>          Desktop
2019/03/18  14:54    <DIR>          Documents
2019/03/22  10:56    <DIR>          Downloads
2019/01/22  16:39    <DIR>          Favorites
2019/03/19  10:59    <DIR>          git0319
2019/01/22  16:39    <DIR>          Links
2018/07/24  17:15    <DIR>          maxima
2019/02/01  08:30    <DIR>          Music
2018/12/18  16:14    <DIR>          ODBA
2019/03/21  12:54    <DIR>          OneDrive - Teradata
2019/01/28  13:52    <DIR>          Pictures
2019/01/22  16:39    <DIR>          Saved Games
2018/07/24  15:16    <DIR>          seaborn-data
2019/01/22  16:39    <DIR>          Searches
2018/07/31  14:11    <DIR>          Tracing
2018/11/28  11:13               731 Untitled.ipynb
2018/11/28  11:13               287 Untitled1.ipynb
2018/11/28  11:35               287 Untitled2.ipynb
2018/11/28  11:51                72 Untitled3.ipynb
2018/11/28  11:57               728 Untitled4.ipynb
2019/02/12  15:37    <DIR>          Videos
2018/09/28  12:52    <DIR>          workspace-studio
2019/03/19  15:42    <DIR>          新しいフォルダー
               9 個のファイル               3,486 バイト
              39 個のディレクトリ  302,650,454,016 バイトの空き領域

(base) C:\Users\ST186052>cd Documents

(base) C:\Users\ST186052\Documents>dir
 ドライブ C のボリューム ラベルは OS です
 ボリューム シリアル番号は 1EB9-76A5 です

 C:\Users\ST186052\Documents のディレクトリ

2019/03/18  14:54    <DIR>          .
2019/03/18  14:54    <DIR>          ..
2018/09/05  12:42    <DIR>          .idea
2018/11/28  11:48    <DIR>          .ipynb_checkpoints
2018/12/19  11:30    <DIR>          .keras
2018/11/28  14:31    <DIR>          .matplotlib
2019/02/12  09:24                 0 .Rhistory
2018/11/15  13:21    <DIR>          AsterRelated
2019/03/20  13:41    <DIR>          g19
2019/03/18  16:00    <DIR>          MobaXterm
2018/09/12  04:52    <DIR>          My Kindle Content
2019/01/17  08:40    <DIR>          My PDFill
2018/04/11  10:22    <DIR>          Office のカスタム テンプレート
2018/11/28  10:59    <DIR>          Python Scripts
2018/11/14  16:20    <DIR>          R
2019/03/13  17:07    <DIR>          suzuki_analytics
2019/03/12  14:22    <DIR>          szk_DL
2019/02/12  07:59    <DIR>          trash
2019/03/12  15:09               465 Untitled.ipynb
2018/09/10  17:09    <DIR>          マイ Tableau リポジトリ
               2 個のファイル                 465 バイト
              18 個のディレクトリ  302,650,454,016 バイトの空き領域

(base) C:\Users\ST186052\Documents>cd suzuki_analytics

(base) C:\Users\ST186052\Documents\suzuki_analytics>dir
 ドライブ C のボリューム ラベルは OS です
 ボリューム シリアル番号は 1EB9-76A5 です

 C:\Users\ST186052\Documents\suzuki_analytics のディレクトリ

2019/03/13  17:07    <DIR>          .
2019/03/13  17:07    <DIR>          ..
2019/03/12  13:08             1,396 .gitignore
2019/03/12  13:08               122 .gitmodules
2019/03/22  10:56    <DIR>          data
2019/03/12  13:08             2,678 README.md
2019/03/12  13:08    <DIR>          reports
2019/03/22  10:27    <DIR>          src
2019/03/12  13:08    <DIR>          tests
               3 個のファイル               4,196 バイト
               6 個のディレクトリ  302,650,519,552 バイトの空き領域

(base) C:\Users\ST186052\Documents\suzuki_analytics>python src\scripts\fit_trees.py --WorkflowRunner.config_file="C:\Users\ST186052\Documents\suzuki_analytics\data\interim\test0322\fit_trees.config.py"
C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
Loading postgres module without psycopg2 installed. Will crash at runtime if postgres functionality is used.
C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\site-packages\luigi\parameter.py:284: UserWarning: Parameter "task_process_context" with value "None" is not of type string.
  warnings.warn('Parameter "{}" with value "{}" is not of type string.'.format(param_name, param_value))
Traceback (most recent call last):
  File "src\scripts\fit_trees.py", line 357, in <module>
    main()
  File "src\scripts\fit_trees.py", line 353, in main
    WorkflowRunner.launch_instance(main_task_cls=Fit)
  File "C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\ST186052\Documents\suzuki_analytics\src\configurable_luigi\runner.py", line 32, in start
    **self.run_options
  File "C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\site-packages\luigi\interface.py", line 274, in build
    return _schedule_and_run(tasks, worker_scheduler_factory, override_defaults=env_params)['success']
  File "C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\site-packages\luigi\interface.py", line 208, in _schedule_and_run
    logger.info(execution_summary.summary(worker))
  File "C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\site-packages\luigi\execution_summary.py", line 424, in summary
    return _summary_wrap(_summary_format(_summary_dict(worker), worker))
  File "C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\site-packages\luigi\execution_summary.py", line 358, in _summary_format
    str_output += '{0}\n'.format(_get_str(group_tasks[status], status in _PENDING_SUB_STATUSES))
  File "C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\site-packages\luigi\execution_summary.py", line 148, in _get_str
    params = _get_set_of_params(tasks)
  File "C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\site-packages\luigi\execution_summary.py", line 191, in _get_set_of_params
    params[param] = {getattr(task, param[0]) for task in tasks}
  File "C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\site-packages\luigi\execution_summary.py", line 191, in <setcomp>
    params[param] = {getattr(task, param[0]) for task in tasks}
TypeError: unhashable type: 'dict'

(base) C:\Users\ST186052\Documents\suzuki_analytics>python src\scripts\cleansing.py
Loading postgres module without psycopg2 installed. Will crash at runtime if postgres functionality is used.
C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\site-packages\luigi\parameter.py:284: UserWarning: Parameter "task_process_context" with value "None" is not of type string.
  warnings.warn('Parameter "{}" with value "{}" is not of type string.'.format(param_name, param_value))
C:\Users\ST186052\Documents\suzuki_analytics\src\data\filter.py:41: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return df[~df[col].str.contains(pattern)]
100%|????????????????????????????????????????????????????????????????????????| 276668/276668 [02:12<00:00, 2092.57it/s]
100%|????????????????????????????????????????????????????????????????????????| 306509/306509 [01:08<00:00, 4448.84it/s]
(base) C:\Users\ST186052\Documents\suzuki_analytics>python src\scripts\single-use\20190227-filter_target_data.py
Loading postgres module without psycopg2 installed. Will crash at runtime if postgres functionality is used.
Traceback (most recent call last):
  File "src\scripts\single-use\20190227-filter_target_data.py", line 49, in <module>
    from scripts.get_similar_docs import extract_similar_docs
ModuleNotFoundError: No module named 'scripts.get_similar_docs'

(base) C:\Users\ST186052\Documents\suzuki_analytics>
(base) C:\Users\ST186052\Documents\suzuki_analytics>
(base) C:\Users\ST186052\Documents\suzuki_analytics>python src\scripts\single-use\20190227-filter_target_data.py
Loading postgres module without psycopg2 installed. Will crash at runtime if postgres functionality is used.
Traceback (most recent call last):
  File "src\scripts\single-use\20190227-filter_target_data.py", line 92, in <module>
    sep='\t'
  File "C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1695, in __init__
    src = open(src, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ST186052\\Documents\\suzuki_analytics\\src\\scripts\\single-use\\..\\..\\..\\data/interim/cleansed-text-joined_F_FAULT_PROPOSAL_LL-F_FAULT_WHEN_LL-F_FAULT_SITUATION_LL/filtered-parsed_docs_chasen.csv'

(base) C:\Users\ST186052\Documents\suzuki_analytics>
(base) C:\Users\ST186052\Documents\suzuki_analytics>
(base) C:\Users\ST186052\Documents\suzuki_analytics>python src\scripts\single-use\20190227-filter_target_data.py
Loading postgres module without psycopg2 installed. Will crash at runtime if postgres functionality is used.
Traceback (most recent call last):
  File "src\scripts\single-use\20190227-filter_target_data.py", line 92, in <module>
    sep='\t'
  File "C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1695, in __init__
    src = open(src, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\data\\interim\\cleansed-text-joined_8764762445972550576\\filtered-parsed_docs_chasen.csv'

(base) C:\Users\ST186052\Documents\suzuki_analytics>python --version
Python 3.6.7 :: Anaconda, Inc.

(base) C:\Users\ST186052\Documents\suzuki_analytics>python src\scripts\single-use\20190227-filter_target_data.py
> c:\users\st186052\documents\suzuki_analytics\src\scripts\single-use\20190227-filter_target_data.py(42)<module>()
-> DATA_PATH = path.join(PRJ_ROOT, 'data')
(Pdb) __file__
'src\\scripts\\single-use\\20190227-filter_target_data.py'
(Pdb) path.abspath(__file__)
'C:\\Users\\ST186052\\Documents\\suzuki_analytics\\src\\scripts\\single-use\\20190227-filter_target_data.py'
(Pdb) PRJ_ROOT
'C:\\Users\\ST186052\\Documents\\suzuki_analytics\\src\\scripts\\single-use\\..\\..\\..'
(Pdb) PARSED_FILE_PATH = path.join(PRJ_ROOT, r"\data\interim\cleansed-text-joined_8764762445972550576\filtered-parsed_docs_chasen.csv")
(Pdb)
(Pdb) pd.read_csv(PARSED_FILE_PATH)
*** FileNotFoundError: File b'C:\\data\\interim\\cleansed-text-joined_8764762445972550576\\filtered-parsed_docs_chasen.csv' does not exist
(Pdb)
Traceback (most recent call last):
  File "src\scripts\single-use\20190227-filter_target_data.py", line 42, in <module>
    from pdb import set_trace; set_trace()
  File "src\scripts\single-use\20190227-filter_target_data.py", line 42, in <module>
    from pdb import set_trace; set_trace()
  File "C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\bdb.py", line 51, in trace_dispatch
    return self.dispatch_line(frame)
  File "C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\bdb.py", line 70, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

(base) C:\Users\ST186052\Documents\suzuki_analytics>python src\scripts\single-use\20190227-filter_target_data.py
Traceback (most recent call last):
  File "src\scripts\single-use\20190227-filter_target_data.py", line 41, in <module>
    PRJ_ROOT = pathlib.Path(__file__).absolute().pardir().pardir().pardir().pardir()
AttributeError: 'WindowsPath' object has no attribute 'pardir'

(base) C:\Users\ST186052\Documents\suzuki_analytics>python src\scripts\single-use\20190227-filter_target_data.py
Loading postgres module without psycopg2 installed. Will crash at runtime if postgres functionality is used.
Traceback (most recent call last):
  File "src\scripts\single-use\20190227-filter_target_data.py", line 93, in <module>
    sep='\t'
  File "C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\ST186052\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1695, in __init__
    src = open(src, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\data\\interim\\cleansed-text-joined_8764762445972550576\\filtered-parsed_docs_chasen.csv'

(base) C:\Users\ST186052\Documents\suzuki_analytics>python src\scripts\single-use\20190227-filter_target_data.py
Loading postgres module without psycopg2 installed. Will crash at runtime if postgres functionality is used.
Traceback (most recent call last):
  File "src\scripts\single-use\20190227-filter_target_data.py", line 114, in <module>
    from ipdb import set_trace; set_trace()
ModuleNotFoundError: No module named 'ipdb'

(base) C:\Users\ST186052\Documents\suzuki_analytics>python src\scripts\single-use\20190227-filter_target_data.py
Loading postgres module without psycopg2 installed. Will crash at runtime if postgres functionality is used.

(base) C:\Users\ST186052\Documents\suzuki_analytics>